// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDXLlx70Rkolcz2n6fcCCk7Am1iK7Ymn0',
    appId: '1:415662373559:android:f10a8633c4d61deb79ab32',
    messagingSenderId: '415662373559',
    projectId: 'zoomclone-30d1d',
    databaseURL: 'https://zoomclone-30d1d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'zoomclone-30d1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVZ7eexliCV2he8kFA_nckkKLlZnWDEYA',
    appId: '1:415662373559:ios:ef41cbfbcae48cca79ab32',
    messagingSenderId: '415662373559',
    projectId: 'zoomclone-30d1d',
    databaseURL: 'https://zoomclone-30d1d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'zoomclone-30d1d.appspot.com',
    androidClientId: '415662373559-kohvu9di18t57vd9i66u57uu8s9ocd4p.apps.googleusercontent.com',
    iosClientId: '415662373559-gak6l6kjnns8iormlqiuj5tumo3i3g8i.apps.googleusercontent.com',
    iosBundleId: 'y',
  );
}
